In [13]:
"""
Excersie number:11
Start date     :20/08/2023
End date       :20/08/2023
Description    :To perform basic numpy operations
"""
import numpy as np
array1=np.array([[2,5,6],[6,8,4]],dtype=float)
array2=np.array([[7,6,3],[3,7,4]],dtype=float)
Add_array=np.add(array1,array2)
Sub_array=np.subtract(array1,array2)
Mul_array=np.multiply(array1,array2)
Div_array=np.divide(array1,array2)
print("The first array is\n",array1)
print("The second array is\n",array2)
print("Addition of two arrays")
print(Add_array)
print("Subtraction of two arrays")
print(Sub_array)
print("Multiplication of two arrays")
print(Mul_array)
print("Division of two arrays")
print(Div_array)
print("The reciprocal of an array is")
print(np.reciprocal(array1))
print("Squaring the elements of an array")
print(np.power(array1,2))
print("Getting the remainder of two arrays")
print(np.mod(array1,array2))

The first array is
 [[2. 5. 6.]
 [6. 8. 4.]]
The second array is
 [[7. 6. 3.]
 [3. 7. 4.]]
Addition of two arrays
[[ 9. 11.  9.]
 [ 9. 15.  8.]]
Subtraction of two arrays
[[-5. -1.  3.]
 [ 3.  1.  0.]]
Multiplication of two arrays
[[14. 30. 18.]
 [18. 56. 16.]]
Division of two arrays
[[0.28571429 0.83333333 2.        ]
 [2.         1.14285714 1.        ]]
The reciprocal of an array is
[[0.5        0.2        0.16666667]
 [0.16666667 0.125      0.25      ]]
Squaring the elements of an array
[[ 4. 25. 36.]
 [36. 64. 16.]]
Getting the remainder of two arrays
[[2. 5. 0.]
 [0. 1. 0.]]
